GET http://localhost:5114/books

###
GET http://localhost:5114/books/2

###
POST http://localhost:5114/books
Content-Type: application/json

{
    "name": "The Shining",
    "author": "Stephen King",
    "genre": "Horror",
    "price": 9.99,
    "releasedate": "2013-08-27"
}

###
PUT http://localhost:5114/books/1
Content-Type: application/json

{
    "name": "Name Of The Wind",
    "author": "Patrick Rothfuss",
    "genre": "Fantasy",
    "price": 19.99,
    "releaseDate": "2009-05-15"
}

###
DELETE http://localhost:5114/books/1