GET http://localhost:5114/books

###
GET http://localhost:5114/books/2

###
POST http://localhost:5114/books
Content-Type: application/json

{
    "name": "Harry Potter IV Goblet of Fire",
    "author": "J.K. Rowling",
    "genreId": 1,
    "price": 19.99,
    "releasedate": "2000-07-08"
}

###
PUT http://localhost:5114/books/3
Content-Type: application/json

{
    "name": "Harry Potter IV Goblet of Fire",
    "author": "J.K. Rowling",
    "genreId": 1,
    "price": 29.99,
    "releasedate": "2000-07-08"
}

###
DELETE http://localhost:5114/books/3